# environment.yml
name: mygene-mcp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - mcp>=1.0.0
    - httpx>=0.27.0
    - pydantic>=2.0.0
    - pytest>=8.0.0
    - pytest-asyncio>=0.23.0
    - pytest-cov>=4.0.0
    - black>=24.0.0
    - ruff>=0.4.0
    - mypy>=1.10.0
    - -e .